
required = ["k8s.io/code-generator/cmd/client-gen"]

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.13"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.13"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.13"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.13"

[[constraint]]
  name = "k8s.io/apiserver"
  branch = "release-1.13"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-10.0"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.13"
